### ISSUE TITLE
Cannot read property 'blurkit' of undefined

### ISSUE THREAD

**Issue by xeroxstar** [davecoffin/nativescript-blur#6]
Hello, i am trying to run a blur test on image, but i get error Cannot read property 'blurkit' of undefined:

`System.err: TypeError: Cannot read property 'blurkit' of undefined
System.err: File: "file:///data/data/org.nativescript.application/files/app/app.js, line: 1, column: 14485
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'e', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 146404
System.err: 	Frame: function:'onTap', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 146147
System.err: 	Frame: function:'n', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 6984
System.err: 	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 16227
System.err: 	Frame: function:'e.$emit', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 113488
System.err: 	Frame: function:'onTap', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 141808
System.err: 	Frame: function:'n', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 6984
System.err: 	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 16227
System.err: 	Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 103, column: 23
System.err: 	Frame: function:'Observable._emit', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 120, column: 18
System.err: 	Frame: function:'ClickListenerImpl.onClick', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/button/button.js', line: 26, column: 23
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err: 	at com.tns.gen.java.lang.Object_button_19_32_ClickListenerImpl.onClick(Object_button_19_32_ClickListenerImpl.java:12)
System.err: 	at android.view.View.performClick(View.java:6261)
System.err: 	at android.widget.TextView.performClick(TextView.java:11157)
System.err: 	at android.view.View$PerformClick.run(View.java:23748)
System.err: 	at android.os.Handler.handleCallback(Handler.java:751)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:154)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6776)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
ActivityManager: Process org.nativescript.application (pid 5444) has died(206,892)
ActivityManager: cleanUpApplicationRecord -- 5444
`

Maybe i am missing some packages?

**Comment by shiv19** [comment]
All you need to do is `tns platform remove android`
And then `tns run android`
